server:
  port: 8081
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: 123
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:/Mapper/*Mapper.xml